version: "3"

vars:
  ENVOY_FILTER_WASM: "main.wasm"
  ENVOY_FILTER_CONFIG: "docs/envoy.yaml"

tasks:
  build:
    desc: Build the go binary using tinygo and docker
    cmds:
       - tinygo build -o {{.ENVOY_FILTER_WASM}} -scheduler=none -target=wasi ./main.go
    sources:
      - ./*.go
    generates:
      - "{{.output}}"
    method: timestamp

  run:
    desc: Run {{.ENVOY_FILTER_WASM}} on envoy container
    deps: [ build ]
    cmds:
      - defer: { task: clean }
      - |
        docker run -it --rm \
          --name envoy-runner \
          -v $PWD/{{.ENVOY_FILTER_CONFIG}}:/etc/envoy/envoy.yaml \
          -v $PWD/{{.ENVOY_FILTER_WASM}}:/etc/envoy/{{.ENVOY_FILTER_WASM}} \
          -p 8001:8001 \
          -p 38140:38140 \
          -p 18000:18000 \
          envoyproxy/envoy:v1.20.0 \
          --component-log-level upstream:debug \
          -c /etc/envoy/envoy.yaml

  infra:deploy:
   deps: [ build ]
   cmds:
     - kustomize build ./infra | kubectl apply -f --

  infra:clean:
    cmds:
      - kustomize build ./infra | kubectl delete -f --

  clean:
    ignore_error: true
    cmds:
      - docker stop envoy-runner