name: WASM Filter Written With Go
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tinygo: ['0.24.0', '0.25.0']
    name: TinyGo ${{ matrix.tinygo }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: ${{ matrix.tinygo }}
d
